# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a GPL-3.0
# license that can be found in the LICENSE file.

version: "3"

services:
  midgard:
    container_name: midgard
    restart: always
    volumes:
      - ../data:/app/data
    image: midgard:latest
    environment:
      MIDGARD_CONF: /app/config.yml
    cap_add:
      - SYS_PTRACE # for debugging
    ports:
      - "9124:9124"
